services:
  web:
    build: .
    container_name: django_app
    command: >
      bash -c "
        python manage.py makemigrations &&
        python manage.py migrate && 
        python createsuperuser.py &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - /var/log/postgresql:/var/log/postgresql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: