# Generated by Django 5.2.5 on 2025-08-14 07:20

import src.commons.choices.booklng_status
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miet_angebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=src.commons.choices.booklng_status.BookingStatusChoice.choices, max_length=100, null=True),
        ),
    ]
