# Generated by Django 5.2.5 on 2025-08-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miet_angebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='count_views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
