# Generated by Django 5.2.5 on 2025-08-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miet_angebot', '0002_listing_count_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=255, unique=True)),
                ('counter', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
