# Generated by Django 5.2.5 on 2025-08-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miet_angebot', '0002_booking_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('can_decline_booking', 'Can decline booking'), ('can_cancel_booking', 'Can cansel booking'), ('can_accept_booking', 'Can accept booking')]},
        ),
    ]
