# Generated by Django 5.2.5 on 2025-08-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miet_angebot', '0003_searchwords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchwords',
            options={'ordering': ['-counter']},
        ),
    ]
