# Generated by Django 5.2.5 on 2025-08-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miet_angebot', '0003_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rooms_count',
            field=models.CharField(choices=[('one_rums', 'one_rums'), ('two_rums', 'two_rums'), ('three_rums', 'three_rums'), ('four und mer', 'four und mer'), ("{1: 'one_rums', 2: 'two_rums', 3: 'three_rums', 4: 'four und mer'}", "{1: 'one_rums', 2: 'two_rums', 3: 'three_rums', 4: 'four und mer'}")], max_length=100),
        ),
    ]
