# Generated by Django 5.2.5 on 2025-08-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miet_angebot', '0004_alter_listing_rooms_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms_count',
            field=models.CharField(choices=[('one_rums', 'one_rums'), ('two_rums', 'two_rums'), ('three_rums', 'three_rums'), ('four und mer', 'four und mer')], max_length=100),
        ),
    ]
