# Generated by Django 5.2.5 on 2025-08-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miet_angebot', '0005_alter_listing_options_alter_listing_rooms_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'permissions': [('can_decline_booking', 'Can decline booking'), ('can_cancel_booking', 'Can cansel booking'), ('can_accept_booking', 'Can accept booking')]},
        ),
    ]
