# Generated by Django 5.2.5 on 2025-08-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miet_angebot', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
